iflx – double mach reflection problem
iflx Subroutine
68 statements
Source File
subroutine iflx()
x方向格子点数 y方向格子点数 時間刻み幅 比熱比と関連定数 定数（計算速度性能に寄与するかはよくわからない）
Arguments
None
Calls
Called by
Contents
Common Blocks
sval flux sflr nvec
Common Blocks
common /sval/
Type Attributes Name Initial
real :: pxl(4,0:jmax+1,0:kmax+1)
real :: pxr(4,0:jmax+1,0:kmax+1)
real :: pyl(4,0:jmax+1,0:kmax+1)
real :: pyr(4,0:jmax+1,0:kmax+1)
common /flux/
Type Attributes Name Initial
real :: xflx(4,jmax,kmax)
real :: yflx(4,jmax,kmax)
common /sflr/
Type Attributes Name Initial
real :: conL(4)
real :: conR(4)
real :: dnflx(4)
common /nvec/
Type Attributes Name Initial
real :: dnx
real :: dny
Call graph
iflx calls pxl, slau, pxr, conr, pyl, conl, xflx, dnflx, pyr, yflx
slau calls conr, conl, dnflx, dsign
main calls iflx