init – double mach reflection problem
init Subroutine
79 statements
Source File
subroutine init()
x方向格子点数 y方向格子点数 時間刻み幅 比熱比と関連定数 定数（計算速度性能に寄与するかはよくわからない）
Arguments
None
Calls
Called by
Contents
Common Blocks
stt0 stt1 mesh cons pris
Common Blocks
common /stt0/
Type Attributes Name Initial
real :: r0
real :: p0
real :: u0
real :: v0
real :: ru0
real :: rv0
real :: e0
common /stt1/
Type Attributes Name Initial
real :: r1
real :: p1
real :: u1
real :: v1
real :: ru1
real :: rv1
real :: e1
common /mesh/
Type Attributes Name Initial
real :: x(0:jmax+1,0:kmax+1)
real :: y(0:jmax+1,0:kmax+1)
common /cons/
Type Attributes Name Initial
real :: cons(4,0:jmax+1,0:kmax+1)
common /pris/
Type Attributes Name Initial
real :: pris(4,0:jmax+1,0:kmax+1)
Call graph
init calls y, pris, dsign, x, cons
main calls init