intg – double mach reflection problem
intg Subroutine
23 statements
Source File
subroutine intg()
Arguments
None
Calls
Called by
Contents
Common Blocks
flux cons dflx dlxy
Common Blocks
common /flux/
Type Attributes Name Initial
real :: xflx(4,jmax,kmax)
real :: yflx(4,jmax,kmax)
common /cons/
Type Attributes Name Initial
real :: cons(4,0:jmax+1,0:kmax+1)
common /dflx/
Type Attributes Name Initial
real :: df(4,jmax,kmax)
common /dlxy/
Type Attributes Name Initial
real :: dltx
real :: dlty
Call graph
intg calls df, xflx, yflx
main calls intg