intp – double mach reflection problem
intp Subroutine
67 statements
Source File
subroutine intp()
y
Arguments
None
Calls
Called by
Contents
Common Blocks
pris sval
Common Blocks
common /pris/
Type Attributes Name Initial
real :: pris(4,0:jmax+1,0:kmax+1)
common /sval/
Type Attributes Name Initial
real :: pxl(4,0:jmax+1,0:kmax+1)
real :: pxr(4,0:jmax+1,0:kmax+1)
real :: pyl(4,0:jmax+1,0:kmax+1)
real :: pyr(4,0:jmax+1,0:kmax+1)
Call graph
intp calls pris, dsign, pxr, pyr, pxl, pyl
main calls intp