slau – double mach reflection problem
slau Subroutine
47 statements
Source File
subroutine slau()
Arguments
None
Calls
Called by
Contents
Common Blocks
sflr nvec
Common Blocks
common /sflr/
Type Attributes Name Initial
real :: conL(4)
real :: conR(4)
real :: dnflx(4)
common /nvec/
Type Attributes Name Initial
real :: dnx
real :: dny
Call graph
slau calls conl, dsign, conr, dnflx
iflx calls slau
main calls iflx