main – double mach reflection problem
main Program
86 statements
Source File
x方向格子点数 y方向格子点数 時間刻み幅 比熱比と関連定数 定数（計算速度性能に寄与するかはよくわからない） パラメータ等設定 includeを用いるのは本来好ましくない 最大反復数 終了時間
Calls
Contents
Common Blocks
mesh dlxy cons pris time loop stt0 stt1 flux sval dflx sflr nvec
Variables
conn
Common Blocks
common /mesh/
格子点座標 0とmax+1は便宜上 計算領域は0-max
Type Attributes Name Initial
real :: x(0:jmax+1,0:kmax+1)
real :: y(0:jmax+1,0:kmax+1)
common /dlxy/
$
Todo
逆数を定義しておく intgがちょっと速くなるはず
Type Attributes Name Initial
real :: dltx
real :: dlty
common /cons/
保存量
Type Attributes Name Initial
real :: cons(4,0:jmax+1,0:kmax+1)
common /pris/
基本量
Type Attributes Name Initial
real :: pris(4,0:jmax+1,0:kmax+1)
common /time/
t:現在時間, tt:サブステップの時間
Type Attributes Name Initial
real :: tn
real :: tt
common /loop/
反復数
Type Attributes Name Initial
integer :: im
common /stt0/
before shock state
Type Attributes Name Initial
real :: r0
real :: p0
real :: u0
real :: v0
real :: ru0
real :: rv0
real :: e0
common /stt1/
after shock state
Type Attributes Name Initial
real :: r1
real :: p1
real :: u1
real :: v1
real :: ru1
real :: rv1
real :: e1
common /flux/
非粘性流束
Type Attributes Name Initial
real :: xflx(4,jmax,kmax)
real :: yflx(4,jmax,kmax)
common /sval/
流束評価面に補間された値 l:left, r:right
Type Attributes Name Initial
real :: pxl(4,0:jmax+1,0:kmax+1)
real :: pxr(4,0:jmax+1,0:kmax+1)
real :: pyl(4,0:jmax+1,0:kmax+1)
real :: pyr(4,0:jmax+1,0:kmax+1)
common /dflx/
時間増分
Type Attributes Name Initial
real :: df(4,jmax,kmax)
common /sflr/
非粘性流束評価で用いる値
Type Attributes Name Initial
real :: conL(4)
real :: conR(4)
real :: dnflx(4)
common /nvec/
流束評価面の法線ベクトル
Type Attributes Name Initial
real :: dnx
real :: dny
Variables
Type Attributes Name Initial
double precision :: conn(4,0:jmax+1,0:kmax+1)
n stepの保存量の一時的置き場
Call graph
main calls grid, c2p, cons, intg, df, init, outf, stbc, intp, iflx
grid calls x, y
c2p calls cons, pris
intg calls df, xflx, yflx
init calls cons, x, y, pris, dsign
outf calls cons
stbc calls cons, x, dsign
intp calls pris, dsign, pyl, pxr, pxl, pyr
iflx calls pyl, pxr, pxl, slau, conr, xflx, yflx, pyr, conl, dnflx
slau calls dsign, conr, conl, dnflx